DROP FUNCTION IF EXISTS user_file_access;
DROP VIEW IF EXISTS file_access;
DROP TABLE IF EXISTS shared_files;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS unique_uuid;
DROP FUNCTION IF EXISTS uuids_from_table;
DROP EXTENSION IF EXISTS "uuid-ossp";